<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Aggregates\Users\Entities\Communities\**" />
    <EmbeddedResource Remove="Aggregates\Users\Entities\Communities\**" />
    <None Remove="Aggregates\Users\Entities\Communities\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UseCases\Lumen.Users.UseCases\Lumen.Profile.UseCases.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Aggregates\Communities\" />
    <Folder Include="Aggregates\Users\Entities\Posts\Queries\" />
  </ItemGroup>

</Project>
