<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Users\Queries\**" />
    <EmbeddedResource Remove="Users\Queries\**" />
    <None Remove="Users\Queries\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UseCase\Lumen.Identity.UseCase\Lumen.Identity.UseCase.csproj" />
  </ItemGroup>

</Project>
