// <auto-generated />
using System;
using Lumen.Profile.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lumen.Users.Infrastructure.Migrations
{
    [DbContext(typeof(LumenDbContext))]
    partial class LumenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Communities.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.Entities.CommentImages.CommentImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("OwnerId");

                    b.ToTable("CommentImages");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.Entities.PostImages.PostImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PostId");

                    b.ToTable("PostImages");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.Entities.Posts.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.Entities.RootAnswerComments.RootAnswerComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RootId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RootId");

                    b.ToTable("RootAnswerComments");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.Entities.RootComments.RootComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Communities.Community", b =>
                {
                    b.HasOne("Lumen.Profile.Domain.Aggregates.Users.User", "Owner")
                        .WithMany("CreatedCommunities")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.Entities.CommentImages.CommentImage", b =>
                {
                    b.HasOne("Lumen.Profile.Domain.Aggregates.Users.Entities.RootComments.RootComment", "Comment")
                        .WithMany("Images")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumen.Profile.Domain.Aggregates.Users.User", "Owner")
                        .WithMany("CommentImages")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.Entities.PostImages.PostImage", b =>
                {
                    b.HasOne("Lumen.Profile.Domain.Aggregates.Users.User", "Owner")
                        .WithMany("PostImages")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumen.Profile.Domain.Aggregates.Users.Entities.Posts.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.Entities.Posts.Post", b =>
                {
                    b.HasOne("Lumen.Profile.Domain.Aggregates.Communities.Community", "Community")
                        .WithMany("Posts")
                        .HasForeignKey("CommunityId");

                    b.HasOne("Lumen.Profile.Domain.Aggregates.Users.User", "Owner")
                        .WithMany("Posts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.Entities.RootAnswerComments.RootAnswerComment", b =>
                {
                    b.HasOne("Lumen.Profile.Domain.Aggregates.Users.User", "Owner")
                        .WithMany("RootAnswerComments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumen.Profile.Domain.Aggregates.Users.Entities.RootComments.RootComment", "Root")
                        .WithMany("Answers")
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Root");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.Entities.RootComments.RootComment", b =>
                {
                    b.HasOne("Lumen.Profile.Domain.Aggregates.Users.User", "Owner")
                        .WithMany("RootComments")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumen.Profile.Domain.Aggregates.Users.Entities.Posts.Post", "Post")
                        .WithMany("RootComments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.User", b =>
                {
                    b.OwnsOne("Lumen.Profile.Domain.Aggregates.Users.ValueObjects.About.About", "About", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AvatarUrl")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("AvatarUrl");

                            b1.Property<DateOnly?>("BirthDate")
                                .HasColumnType("date")
                                .HasColumnName("BirthDate");

                            b1.Property<string>("CurrentCity")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CurrentCity");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Description");

                            b1.Property<string>("Gender")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Gender");

                            b1.Property<bool>("HasPublicProfile")
                                .HasColumnType("boolean")
                                .HasColumnName("HasPublicProfile");

                            b1.Property<string>("Hometown")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Hometown");

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Language");

                            b1.Property<string>("MaritalStatus")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MaritalStatus");

                            b1.Property<string>("PersonalSite")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PersonalSite");

                            b1.Property<string>("SchoolName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SchoolName");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Lumen.Profile.Domain.Aggregates.Users.ValueObjects.Email.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Lumen.Profile.Domain.Aggregates.Users.ValueObjects.LastName.LastName", "LastName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("LastName");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Lumen.Profile.Domain.Aggregates.Users.ValueObjects.Name.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Name");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Lumen.Profile.Domain.Aggregates.Users.ValueObjects.Surname.Surname", "Surname", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Surname");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Lumen.Profile.Domain.Aggregates.Users.ValueObjects.UserName.UserName", "UserName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("UserName");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("About")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("LastName")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Surname")
                        .IsRequired();

                    b.Navigation("UserName")
                        .IsRequired();
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Communities.Community", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.Entities.Posts.Post", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("RootComments");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.Entities.RootComments.RootComment", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Lumen.Profile.Domain.Aggregates.Users.User", b =>
                {
                    b.Navigation("CommentImages");

                    b.Navigation("CreatedCommunities");

                    b.Navigation("PostImages");

                    b.Navigation("Posts");

                    b.Navigation("RootAnswerComments");

                    b.Navigation("RootComments");
                });
#pragma warning restore 612, 618
        }
    }
}
