<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Messages\Community\" />
    <Folder Include="Messages\Post\" />
    <Folder Include="Messages\RootCommentAnswer\" />
    <Folder Include="Messages\RootComment\" />
    <Folder Include="Messages\User\" />
  </ItemGroup>

</Project>
